// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1614697985);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.log.file", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 807);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1614697921);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "yandex");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://yandex.com\",\"label\":\"@яндекс\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"screenshots_mozilla_org\",\"webcompat-reporter_mozilla_org\"],\"idsInUrlbar\":[\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1614697750018");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1614719350018");
user_pref("browser.search.region", "RU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210223094543");
user_pref("browser.slowStartup.averageTime", 4032);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20210223094543");
user_pref("browser.startup.homepage_override.mstone", "78.8.0");
user_pref("browser.startup.lastColdStartupCheck", 1614697957);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[]},\"seen\":[\"developer-button\",\"profiler-button\"],\"dirtyAreaCache\":[],\"currentVersion\":16,\"newElementCount\":0}");
user_pref("browser.urlbar.placeholderName", "Bing");
user_pref("devtools.theme", "light");
user_pref("distribution.iniFile.exists.appversion", "78.8.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.push.userAgentID", "c75826ca437a4c6dac7b04f4986d8f81");
user_pref("extensions.activeThemeID", "floe@waterfox.net");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210223094543");
user_pref("extensions.lastAppVersion", "78.8.0");
user_pref("extensions.lastPlatformVersion", "78.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon-stores@waterfox.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"a9f63dc7-d3b2-4dfc-9e73-81e8374c5bb5\",\"screenshots@mozilla.org\":\"23758095-b703-430f-9269-c9ba6b78ed2c\",\"webcompat-reporter@mozilla.org\":\"e1823f30-5024-4b12-a72c-ed6054a6384a\",\"webcompat@mozilla.org\":\"376f481d-1ec9-496c-a10e-96d9fda54112\",\"addon-stores@waterfox.net\":\"e7cfdd9a-2b48-46d3-a0ac-98b713368c27\",\"floe@waterfox.net\":\"8da0860b-d7c0-453c-b4f5-88d43d287e1d\",\"bing@search.waterfox.net\":\"dde0d212-dda7-4f0e-b2be-d65f7a6b188c\",\"google@search.waterfox.net\":\"fe53406f-de19-41da-b7af-37534246138f\",\"startpage@search.waterfox.net\":\"378ceaf3-2491-45df-aea6-23143640927c\",\"qwant@search.waterfox.net\":\"24c24d13-4ec1-4c0a-abe8-09cb9ae7d793\",\"ddg@search.waterfox.net\":\"0e3914cb-830a-4e88-9821-13d28eb8129e\",\"yandex@search.waterfox.net\":\"a0b31bc0-a249-4f54-9c1a-e13e284b435c\",\"wikipedia@search.waterfox.net\":\"85ee908b-0e66-4923-811c-0d6dc14c03db\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "f5fa9ff6-6c6c-4410-8664-aaf4e716df62");
user_pref("security.sandbox.plugin.tempDirSuffix", "58321abb-eb29-4775-942b-d4e302326c84");
user_pref("services.blocklist.addons-mlbf.checked", 1614698870);
user_pref("services.blocklist.gfx.checked", 1614698870);
user_pref("services.blocklist.plugins.checked", 1614698870);
user_pref("services.settings.clock_skew_seconds", -885);
user_pref("services.settings.last_etag", "\"1614693510977\"");
user_pref("services.settings.last_update_seconds", 1614698870);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1614698870);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1614698870);
user_pref("services.settings.main.hijack-blocklists.last_check", 1614698870);
user_pref("services.settings.main.language-dictionaries.last_check", 1614698870);
user_pref("services.settings.main.search-config.last_check", 1614698870);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1614698870);
user_pref("services.settings.main.sites-classification.last_check", 1614698870);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1614698870);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1614697954);
user_pref("toolkit.telemetry.cachedClientID", "134aba15-251d-4ef9-b5ea-56a2581b2a21");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
